title: Waterfall Theme

exclude: ['front']

collections:
  experiences:
    output: false

# Uncomment the section below to add items on your top navigation
# header_items:
#   - About:
#     title: About
#     href: "#about"
#   - Work:
#     title: Work
#     href: "#work"
#   - contact.md
#   - Resume:
#     title: Resume
#     href: https://drive.google.com
#     featured: true

waterfall:
  author:
    name: John Doe
    description: Write a great description about you here

  social_links:
    github: jekyll    
    linkedin: jekyll
    email: jekyll@jekyll.io