title: Waterfall Theme

exclude: ['front']

collections:
  experiences:
    output: false
  projects:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Uncomment the section below to add items on your top navigation
# header_items:
#   -
#     title: Projects
#     href: "/projects"
#   - contact.md
#   -
#     title: Resume
#     href: https://drive.google.com
#     featured: true

waterfall:
  author:
    name: John Doe
    description: Write a great description about you here

  social_links:
    github: jekyll    
    linkedin: jekyll
    email: jekyll@jekyll.io

analytics:
  tracking_id: "UX-12345678"

disqus:
  shortname: jekyll